-- Create tasks table
create table public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  priority text check (priority in ('Low', 'Medium', 'High')),
  status text check (status in ('To-do', 'In Progress', 'Done')),
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.tasks enable row level security;

-- Create Policies
create policy "Users can create their own tasks."
  on public.tasks for insert
  with check (auth.uid() = user_id);

create policy "Users can view their own tasks."
  on public.tasks for select
  using (auth.uid() = user_id);

create policy "Users can update their own tasks."
  on public.tasks for update
  using (auth.uid() = user_id);

create policy "Users can delete their own tasks."
  on public.tasks for delete
  using (auth.uid() = user_id);
